### PR TITLE
Remove name

### PR DESCRIPTION
**Pull request by vladbenchea**
Just like for the memo field, this goes for name in the field selection (it seems it appeared only on GT and MT)

### CODE REVIEW

**Comment by vladbenchea** [comment]
@atothhpe What do you mean? It's not in 2 places, it just verifies two things in order to add it (or not) in the _allEntityFields

**Comment by atothhpe** [comment]
nvm I misread

**Comment by atothhpe** [comment]
@vladbenchea fieldsToHideHashSet , what's in it? can we add name there?

**Comment by atothhpe** [comment]
Also it's not a good idea to decide which field is which based on the label, because the label can be translated in diff octane version, field.Name should always be "name" tho

**Comment by vladbenchea** [comment]
@atothhpe actually this is happening because whenever you refresh an entity, it detects the gherkin test once as of type "test", and once as of type "gherkin_test" - I'm still investigating why this is happening, but I think if I manage to fix so that GT will always be detected of type "gherkin_test", it might fix this also (there are other fields that needs to be removed from the field selection list such as description)

**Pull request closed without merging**
